#!/bin/bash
CURRENT_DIR=$(pwd)

echo "Home Directory is $CURRENT_DIR"
npm i
(cd gui; npm i)
echo "Building GUI"
(cd gui; npm run build)
echo "Restart s1panel..."
systemctl restart s1panel.service
echo "Done!"
systemctl status s1panel.service
